# Generated by Django 3.2 on 2023-04-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
